query portfolio($portfolioId: ID!) {
  portfolio(portfolioId: $portfolioId) {
    __typename
    id
    name
    primary

    transactions {
      id
      asset {
        __typename
        id
        name
        ... on ExchangeTradedAsset {
          ticker
          logo
          ... on Stock {
            __typename
          }
          ... on Crypto {
            __typename
          }
        }
      }
      portfolioId
      executedAt
      value
      volume
    }
  }
}
