module.exports = {
  projects: [
    "<rootDir>/apps/app",
    "<rootDir>/libs/data-access/db",
    "<rootDir>/libs/ui/components",
    "<rootDir>/libs/data-access/api-client",
    "<rootDir>/libs/feature/time",
    "<rootDir>/libs/data-access/iexcloud",
    "<rootDir>/apps/landing",
    "<rootDir>/libs/feature/email",
    "<rootDir>/libs/feature/tokens",
    "<rootDir>/libs/api/feature/lambda",
    "<rootDir>/libs/api/feature/middleware",
    "<rootDir>/libs/data-access/localstorage",
    "<rootDir>/libs/data-access/cache",
    "<rootDir>/libs/types",
    "<rootDir>/libs/data-access/fauna-adapter",
    "<rootDir>/libs/ui/design-system",
  ],
}
