query portfolio($portfolioId: ID!, $since: Int) {
  portfolio(portfolioId: $portfolioId) {
    __typename
    id
    name
    primary

    transactions {
      id
      portfolioId
      assetId
      asset {
        __typename
        id
        name
        ... on ExchangeTradedAsset {
          ticker
          isin
          logo
          ... on Stock {
            __typename
          }
          ... on Crypto {
            __typename
          }
        }
      }

      executedAt
      value
      volume
    }
    relativeHistory(since: $since) {
      time
      value
    }
    absoluteHistory(since: $since) {
      asset {
        __typename
        id
        name
        ... on ExchangeTradedAsset {
          ticker
          isin
          logo
          ... on Stock {
            __typename
          }
          ... on Crypto {
            __typename
          }
        }
      }
      history {
        time
        value
        quantity
      }
    }
  }
}
