query portfolio($portfolioId: ID!, $withHistory: Boolean!) {
  portfolio(portfolioId: $portfolioId, withHistory: $withHistory) {
    __typename
    id
    name
    primary

    transactions {
      id
      portfolioId
      assetId
      asset {
        __typename
        id
        name
        ... on ExchangeTradedAsset {
          ticker
          isin
          logo
          ... on Stock {
            __typename
          }
          ... on Crypto {
            __typename
          }
          
        }
      }

      executedAt
      value
      volume
    }

    absoluteHistory @include(if: $withHistory){
      asset {
        id
      }
    history {
      time
      value
    }
    }
  }
}
