query getCompany($ticker: String!, $withExchange: Boolean!) {
  getCompany(ticker: $ticker) {
    ticker
    logo
    name
    exchange @include(if: $withExchange) {
      name
      mic
    }
    description
    sector
    figi
  }
}
