query getPortfolio($userId: ID!) {
  getPortfolio(userId: $userId) {
    asset {
      ... on Stock {
        id
        ticker
        company {
          currentValue
        }
      }
      ... on Crypto {
        id
        name
      }
    }
  }
}
