query getTransactions($portfolioId: ID!) {
  getTransactions(portfolioId: $portfolioId) {
    __typename

    id
    asset {
      __typename
      id
      ticker
      logo
      name
      ... on CompanyStock {
        __typename
      }
      ... on Crypto {
        __typename
      }
    }
    userId
    executedAt
    value
    volume
  }
}
