query portfolioHistory($portfolioId: ID!) {
  portfolioHistory(portfolioId: $portfolioId) {
    assetId
    asset {
      id
      ticker
      name
      logo

      ... on CompanyStock {
        __typename
        sector
        country
      }

      ... on Crypto {
        __typename
      }
    }
    history {
      value
      time
      quantity
    }
  }
}
