query portfolio($portfolioId: ID!) {
  portfolio(portfolioId: $portfolioId) {
    __typename
    id
    name
    primary

    transactions {
      id
      asset {
        __typename
        id
        ticker
        logo
        name
        ... on CompanyStock {
          __typename
        }
        ... on Crypto {
          __typename
        }
      }
      portfolioId
      executedAt
      value
      volume
    }
  }
}
